### ISSUE TITLE
[BUG] testexec/do.to2.62.execute.go:57 http: panic serving [::1]:50577: runtime error

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/iot-fdo-conformance-tools#48]
To simplify issue resolution process, please provide network logs, and or test voucher.
```
2023/09/27 13:30:05 Requesting GetOVNextEntry62 for entry 5 
2023/09/27 13:30:05 Requesting GetOVNextEntry62 for entry 0 
2023/09/27 13:30:05 Requesting GetOVNextEntry62 for entry 1 
2023/09/27 13:30:05 Requesting GetOVNextEntry62 for entry 2 
2023/09/27 13:30:05 Requesting GetOVNextEntry62 for entry 3 
2023/09/27 13:30:05 http: panic serving [::1]:50577: runtime error: invalid memory address or nil pointer dereference
goroutine 38 [running]:
net/http.(*conn).serve.func1()
        /Users/thaodtp/sdk/go1.19.5/src/net/http/server.go:1850 +0xb0
panic({0x100b20a80, 0x100fb6f50})
        /Users/thaodtp/sdk/go1.19.5/src/runtime/panic.go:890 +0x258
github.com/fido-alliance/fdo-fido-conformance-server/testexec.executeTo2_62({{}, {0x140003e6170, 0x10, 0x10}, {0x1400021c288, 0x15}, 0x2, 0x140007a6420, 0x0, {{}, ...}, ...}, ...)
        /Users/thaodtp/Documents/work/projects/FDO/FA/fdo-fido-conformance-server/testexec/do.to2.62.execute.go:57 +0x434
github.com/fido-alliance/fdo-fido-conformance-server/testexec.ExecuteDOTestsTo2({{}, {0x140003e6170, 0x10, 0x10}, {0x1400021c288, 0x15}, 0x2, 0x140007a6420, 0x0, {{}, ...}, ...}, ...)

```

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
- API: `/api/dot/execute`
- Test case: `FIDO_DOT_62_POSITIVE`
- This is related to https://github.com/fido-alliance/fdo-fido-conformance-server/issues/15
- Observed after debugging:
    - value of `testId` input in `to2requestor.GetOVNextEntry62(uint8(i), testId)` is `FIDO_DOT_62_POSITIVE` https://github.com/fido-alliance/fdo-fido-conformance-server/blob/6d23facb23ff9012ab77fc8b96aeba015f16d683/testexec/do.to2.62.execute.go#L48 
    - For case `FIDO_DOT_62_POSITIVE`, the `GetOVNextEntry62` function returns at this line 
    https://github.com/fido-alliance/fdo-fido-conformance-server/blob/6d23facb23ff9012ab77fc8b96aeba015f16d683/core/device/to2/req-to2-62-GetOVNextEntry.go#L30
   which means the `nextEntry` and `err` are both `nil`, hence panic at this line 
   https://github.com/fido-alliance/fdo-fido-conformance-server/blob/6d23facb23ff9012ab77fc8b96aeba015f16d683/testexec/do.to2.62.execute.go#L57

**Comment by herrjemand** [comment]
Addressed
