### ISSUE TITLE
[BUG] Failure when parsing EMBlock protected header

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/iot-fdo-conformance-tools#54]
To simplify issue resolution process, please provide network logs, and or test voucher.
Msg65 response body: `8343a10101a1054cbf2ca96d7a81bfe3e67beb7d58e3dc6ba21ac9094a7a5b0f09f96527f4902544692c7c720197bd58ec184126bd8f6dcb9e656fbb4759cf2f6844ab53c9484c1a99d0302da52167e369b7d0da5b1942b8d770c45d29bd89e6b44892164f24ebd031bef1e128b95c3df01aeca13aafb933c36e29029fcc7b9c3ca4f0418378765a0e775e15ba91bac24f6af666b626b734f02cd083709f18440c5ebf6390cf8106ce33fc4a6d6414698e134b32dcb52a73cba27a2bdb2d6048f16fc7961eac8a91753b5e0fda9a3298d73a7086f77c4ef583609771df195b626780a630554365f872905a6dfc5706852e35f4e8cc5a753ef4`

Msg65 test result from conformance server:
<img width="764" alt="image" src="https://github.com/fido-alliance/fdo-fido-conformance-server/assets/81215424/1613e2c9-21e3-495c-927f-3f05c649dd7e">

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
Protected header in EMBlock struct is defined as map object instead of bytes array as defined in #6.16 https://www.rfc-editor.org/rfc/rfc8152#section-5.2 
 https://github.com/fido-alliance/fdo-fido-conformance-server/blob/6d23facb23ff9012ab77fc8b96aeba015f16d683/core/shared/enc.crypto.go#L391

**Comment by quanvincss** [comment]
Sorry, I misunderstood the CDDL.

**Comment by herrjemand** [comment]
Haha. No worries @quanvincss

**Comment by quanvincss** [comment]
Hi @herrjemand, I reopen this issue as @GeofCooper said in Discord

<img width="694" alt="image" src="https://github.com/fido-alliance/iot-fdo-conformance-tools/assets/81215424/6293bf4b-0e89-4af8-ae7d-0a4a665e6e22">

**Comment by herrjemand** [comment]
Yes, @GeofCooper is correct.

However this needs to be properly addressed in the spec, and not just a tech note.

cc @pheimfido

**Comment by herrjemand** [comment]
This is now addressed
