### ISSUE TITLE
[BUG] Error generating device EAT

### ISSUE THREAD

**Issue by quanvincss** [fido-alliance/iot-fdo-conformance-tools#56]
To simplify issue resolution process, please provide network logs, and or test voucher.
<img width="719" alt="image" src="https://github.com/fido-alliance/fdo-fido-conformance-server/assets/81215424/f3a30570-c40c-470a-88f7-f0b58dae174e">

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
- Tests failed due to conformance server internal error, screenshot is attached for reference.

**Comment by herrjemand** [comment]
@quanvincss ok, I rewrote good section of that.

Try re-seeding and running test again
