### ISSUE TITLE
[BUG] Replacement rvinfo in message 65 is empty 

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/iot-fdo-conformance-tools#60]
To simplify issue resolution process, please provide network logs, and or test voucher.
[client_replacement_rv_err.log](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/12814619/client_replacement_rv_err.log)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description

- The replacement RVInfo sent by conformance owner in message 65 is empty which is not in accordance with spec as mentioned at https://tinyurl.com/replacementrvinfo which should be same as original (in reuse) or new value (if not reuse). 
- Log is attached for reference

**Comment by herrjemand** [comment]
Adddressed
