### ISSUE TITLE
[BUG] Error in building code on prem

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/iot-fdo-conformance-tools#65]
To simplify issue resolution process, please provide network logs, and or test voucher.
[building_err_log.txt](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/13283803/building_err_log.txt)
[main_go.patch](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/13283938/main_go.patch)

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [ ] Device Onboarding Service
- [x] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [ ] TO2

## Issue description

- When building code on prem, following error is encountered when executing make build command. Logs are attached for reference

```
./main.go:629:3: syntax error: unexpected newline in composite literal; possibly missing comma or }
./main.go:631:26: syntax error: unexpected ) at end of statement

```

- Upon debugging, observed that the issue is with respect to extra parentheses and the patch for the same is attached.

**Comment by herrjemand** [comment]
@Sai-Anudeep47 try latest commit

**Comment by herrjemand** [comment]
@Sai-Anudeep47 fixed with latest commit
