### ISSUE TITLE
[BUG] Invalid EAT-UEID tag and value sent in message 64 by conformance client

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/iot-fdo-conformance-tools#67]
To simplify issue resolution process, please provide network logs, and or test voucher.

## What part of the spec are you testing?

- [ ] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [ ] TO1
- [x] TO2

## Issue description
- In message 64, conformance client sends invalid value `0000000000000000000000000000000000` and wrong tag `11` as part of EATPayloadBaseMap = { EATPayloadBase } which is not in accordance as mentioned in spec at https://tinyurl.com/eatuid
   - The tag should be 256 and value is random value + GUID
- Content of EATPayloadBaseMap in message 64 sent by conformance client is as follows 
```
A30A507E3C1826EA0841B6A68959488EEA47140B5100000000000000000000000000000000003901008158560020CBE3B68E21F79BFE2BD31425E13337920121A30E6AF3E7DCAFADA82C08D0CCF800209CF12917E42D39E1A21A0CFB17A8C46FEC368F2C9F624CDAFDBA356B919B00490010EDCE96A4EFBF7A7E194445500F7B6839
```
- Complete message 64 sent is as follows
```
[h'A10126', {-259: h'E18CEF5D862E5AA843F462276210659F'}, h'A30A507E3C1826EA0841B6A68959488EEA47140B5100000000000000000000000000000000003901008158560020CBE3B68E21F79BFE2BD31425E13337920121A30E6AF3E7DCAFADA82C08D0CCF800209CF12917E42D39E1A21A0CFB17A8C46FEC368F2C9F624CDAFDBA356B919B00490010EDCE96A4EFBF7A7E194445500F7B6839', h'72872E732CD2D2A5A4DEE955743CACA594A45FB629FDFC00EF0996A3AB72ACF875EA16E438CEFFC8FEF3556AFD04676A6D561181E48DE5AB6A6D50407313E068']
```

**Comment by herrjemand** [comment]
Addressed. Thx @Sai-Anudeep47
