### ISSUE TITLE
[BUG] Undesired and invalid values sent for EATPayloadBase  in message 32 and message 64

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/iot-fdo-conformance-tools#68]
To simplify issue resolution process, please provide network logs, and or test voucher.
[msg32_eatpayloadbase_err.txt](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/13352070/msg32_eatpayloadbase_err.txt)
[msg64_eatpayloadbase_err.txt](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/13352164/msg64_eatpayloadbase_err.txt)

## What part of the spec are you testing?

- [x] Rendezvous Server
- [x] Device Onboarding Service
- [ ] Device Implementation

## What protocol are having issue with?

- [ ] TO0
- [x] TO1
- [x] TO2

## Issue description
- In message 32, conformance client sends undesired and invalid values in EATPayloadBase as follows
   - 256: h'0000000000000000000000000000000000' -> This value should be EAT-UEID which is EAT-RAND + current GUID that is mentioned at https://tinyurl.com/eatuid
   - -257:[null] -> This value should not be sent in message 32, as EATPayloads tag is not defined as part of message 32 and mentioned at https://tinyurl.com/msg32eat
- In message 64, conformance client sends invalid value in EATPayloadBase as follows
   - 256: h'0000000000000000000000000000000000' -> This value should be EAT-UEID which is EAT-RAND + current GUID that is mentioned at https://tinyurl.com/eatuid
- Logs are attached for reference that has messages sent by conformance client as part of TO1 and TO2

**Comment by herrjemand** [comment]
Addressed
