### ISSUE TITLE
[BUILD ISSUE] Building the tool with "make build" command returns error

### ISSUE THREAD

**Issue by Sai-Anudeep47** [fido-alliance/iot-fdo-conformance-tools#74]
## What is the OS?

- [ ] OSX
- [ ] Windows
- [x] Linux

## What is the OS version?
- Ubuntu 22.04
- Ubuntu 20.04.5

## What is the tools version? Commit?

d5c20b6151b99610b836ab6dff2a60eef3b42241

## Issue description
When trying to build the tool using `make build` command, following error is observed.

```
go build ./build_helper
go: build output "build_helper" already exists and is a directory
make: *** [Makefile:57: cleanup_frontend] Error 1
```

The above error is due to trying to build a binary with existing folder name in root `Makefile`, the fix for the same is attached as patch file.
[build_fix.patch](https://github.com/fido-alliance/iot-fdo-conformance-tools/files/14464338/build_fix.patch)

**Comment by herrjemand** [comment]
Addressed
